### PR TITLE
use safeTransferFrom

### PR DESCRIPTION
**Pull request by to-sh-1**
reference issue: https://github.com/code-423n4/2022-06-yieldy-findings/issues/206

### CODE REVIEW

**Comment by 0xean** [comment]
The assertion that transfer doesn't revert is incorrect, so this isn't needed, but doesn't harm anything really.

**Comment by to-sh-1** [comment]
> The assertion that transfer doesn't revert is incorrect, so this isn't needed, but doesn't harm anything really.

It still seems valid to not leave it up to the compiler version.  Plus it follows every other transferFrom we are using, so I think it's a fine change

**Comment by 0xean** [comment]
Sounds good.  Worth nothing that if the compiler all of sudden stopped reverting by default on under or overflow, it would break a lot of other functionality as well.  We would have to go back to using SafeMath style libs everywhere as would all other smart contracts written specifically for solidity 0.8.+ that expect this behavior.  It would be a very major breaking change across solidity.

**Comment by to-sh-1** [comment]
> Sounds good. Worth nothing that if the compiler all of sudden stopped reverting by default on under or overflow, it would break a lot of other functionality as well. We would have to go back to using SafeMath style libs everywhere as would all other smart contracts written specifically for solidity 0.8.+ that expect this behavior. It would be a very major breaking change across solidity.

Yea that makes sense.  Maybe that ticket should be moved to low

**Pull request merged**
